// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vbxjlklpetcaatmagiae.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZieGpsa2xwZXRjYWF0bWFnaWFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwODk5OTEsImV4cCI6MjA2NTY2NTk5MX0.8ICFs-bGtOhGCs_qpWp5y5FAngoTvK3mNAEwKYBPt1c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);