// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ghdzwmycmsjvxcqhumon.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdoZHp3bXljbXNqdnhjcWh1bW9uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3Nzg2NzIsImV4cCI6MjA2NjM1NDY3Mn0.alV-vH5aAoLjZWQ4K-WVGVO6ZYkQGNuhwxElPHKi_l4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});